#!/bin/bash 
outputdir=ModuleTolerances_complete_300K_22Nov21
runmacro=ModuleStudies.C
location=.
sysname=Tolerances
source tarCMSSW_hgc.sh $outputdir
 
eosmkdir -p /eos/uscms/store/user/mkilpatr/13TeV/$outputdir
   
echo "$runscript $runmacro $workdir $outputdir"    
./jobs/submitSep_Tolerances_Gaussian_PCBplus000_Kaptonplus000_senTokap185_midSensor.sh
./jobs/submitSep_Tolerances_Gaussian_PCBplus000_Kaptonplus000_senTokap185_newSensor.sh
./jobs/submitSep_Tolerances_Gaussian_PCBplus000_Kaptonplus025_senTokap185_midSensor.sh
./jobs/submitSep_Tolerances_Gaussian_PCBplus000_Kaptonplus025_senTokap185_newSensor.sh
./jobs/submitSep_Tolerances_Gaussian_PCBplus000_Kaptonplus050_senTokap185_midSensor.sh
./jobs/submitSep_Tolerances_Gaussian_PCBplus000_Kaptonplus050_senTokap185_newSensor.sh
./jobs/submitSep_Tolerances_Gaussian_PCBplus000_Kaptonplus075_senTokap185_midSensor.sh
./jobs/submitSep_Tolerances_Gaussian_PCBplus000_Kaptonplus075_senTokap185_newSensor.sh
./jobs/submitSep_Tolerances_Gaussian_PCBplus000_Kaptonplus100_senTokap185_midSensor.sh
./jobs/submitSep_Tolerances_Gaussian_PCBplus000_Kaptonplus100_senTokap185_newSensor.sh
./jobs/submitSep_Tolerances_Gaussian_PCBplus000_Kaptonplus125_senTokap185_midSensor.sh
./jobs/submitSep_Tolerances_Gaussian_PCBplus000_Kaptonplus125_senTokap185_newSensor.sh
./jobs/submitSep_Tolerances_Gaussian_PCBplus000_Kaptonplus150_senTokap185_midSensor.sh
./jobs/submitSep_Tolerances_Gaussian_PCBplus000_Kaptonplus150_senTokap185_newSensor.sh
